package hu.daniinc.reservation.domain;

import static hu.daniinc.reservation.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class BusinessAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessAllPropertiesEquals(Business expected, Business actual) {
        assertBusinessAutoGeneratedPropertiesEquals(expected, actual);
        assertBusinessAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessAllUpdatablePropertiesEquals(Business expected, Business actual) {
        assertBusinessUpdatableFieldsEquals(expected, actual);
        assertBusinessUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessAutoGeneratedPropertiesEquals(Business expected, Business actual) {
        assertThat(actual)
            .as("Verify Business auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUpdatableFieldsEquals(Business expected, Business actual) {
        assertThat(actual)
            .as("Verify Business relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a ->
                assertThat(a.getCreatedDate())
                    .as("check createdDate")
                    //                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedDate())
            )
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a ->
                assertThat(a.getBreakBetweenAppointmentsMin())
                    .as("check breakBetweenAppointmentsMin")
                    .isEqualTo(expected.getBreakBetweenAppointmentsMin())
            )
            .satisfies(a -> assertThat(a.getLogo()).as("check logo").isEqualTo(expected.getLogo()))
            .satisfies(a -> assertThat(a.getBannerUrl()).as("check bannerUrl").isEqualTo(expected.getBannerUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUpdatableRelationshipsEquals(Business expected, Business actual) {
        // empty method
    }
}
