package hu.daniinc.reservation.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BusinessRatingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessRatingAllPropertiesEquals(BusinessRating expected, BusinessRating actual) {
        assertBusinessRatingAutoGeneratedPropertiesEquals(expected, actual);
        assertBusinessRatingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessRatingAllUpdatablePropertiesEquals(BusinessRating expected, BusinessRating actual) {
        assertBusinessRatingUpdatableFieldsEquals(expected, actual);
        assertBusinessRatingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessRatingAutoGeneratedPropertiesEquals(BusinessRating expected, BusinessRating actual) {
        assertThat(actual)
            .as("Verify BusinessRating auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessRatingUpdatableFieldsEquals(BusinessRating expected, BusinessRating actual) {
        assertThat(actual)
            .as("Verify BusinessRating relevant properties")
            .satisfies(a -> assertThat(a.getNumber()).as("check number").isEqualTo(expected.getNumber()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessRatingUpdatableRelationshipsEquals(BusinessRating expected, BusinessRating actual) {
        // empty method
    }
}
