package hu.daniinc.reservation.domain;

import static hu.daniinc.reservation.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class BusinessOpeningHoursAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessOpeningHoursAllPropertiesEquals(BusinessOpeningHours expected, BusinessOpeningHours actual) {
        assertBusinessOpeningHoursAutoGeneratedPropertiesEquals(expected, actual);
        assertBusinessOpeningHoursAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessOpeningHoursAllUpdatablePropertiesEquals(BusinessOpeningHours expected, BusinessOpeningHours actual) {
        assertBusinessOpeningHoursUpdatableFieldsEquals(expected, actual);
        assertBusinessOpeningHoursUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessOpeningHoursAutoGeneratedPropertiesEquals(BusinessOpeningHours expected, BusinessOpeningHours actual) {
        assertThat(actual)
            .as("Verify BusinessOpeningHours auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessOpeningHoursUpdatableFieldsEquals(BusinessOpeningHours expected, BusinessOpeningHours actual) {
        assertThat(actual)
            .as("Verify BusinessOpeningHours relevant properties")
            .satisfies(a -> assertThat(a.getDayOfWeek()).as("check dayOfWeek").isEqualTo(expected.getDayOfWeek()))
            .satisfies(a ->
                assertThat(a.getStartTime())
                    .as("check startTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getStartTime())
            )
            .satisfies(a ->
                assertThat(a.getEndTime()).as("check endTime").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getEndTime())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessOpeningHoursUpdatableRelationshipsEquals(BusinessOpeningHours expected, BusinessOpeningHours actual) {
        // empty method
    }
}
