package hu.daniinc.reservation.domain;

import static hu.daniinc.reservation.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class CustomWorkingHoursAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomWorkingHoursAllPropertiesEquals(CustomWorkingHours expected, CustomWorkingHours actual) {
        assertCustomWorkingHoursAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomWorkingHoursAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomWorkingHoursAllUpdatablePropertiesEquals(CustomWorkingHours expected, CustomWorkingHours actual) {
        assertCustomWorkingHoursUpdatableFieldsEquals(expected, actual);
        assertCustomWorkingHoursUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomWorkingHoursAutoGeneratedPropertiesEquals(CustomWorkingHours expected, CustomWorkingHours actual) {
        assertThat(actual)
            .as("Verify CustomWorkingHours auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomWorkingHoursUpdatableFieldsEquals(CustomWorkingHours expected, CustomWorkingHours actual) {
        assertThat(actual)
            .as("Verify CustomWorkingHours relevant properties")
            .satisfies(a -> assertThat(a.getWorkDate()).as("check workDate").isEqualTo(expected.getWorkDate()))
            .satisfies(a ->
                assertThat(a.getStartTime())
                    .as("check startTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getStartTime())
            )
            .satisfies(a ->
                assertThat(a.getEndTime()).as("check endTime").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getEndTime())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomWorkingHoursUpdatableRelationshipsEquals(CustomWorkingHours expected, CustomWorkingHours actual) {
        assertThat(actual)
            .as("Verify CustomWorkingHours relationships")
            .satisfies(a -> assertThat(a.getBusiness()).as("check business").isEqualTo(expected.getBusiness()));
    }
}
