package hu.daniinc.reservation.domain;

import static hu.daniinc.reservation.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OfferingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferingAllPropertiesEquals(Offering expected, Offering actual) {
        assertOfferingAutoGeneratedPropertiesEquals(expected, actual);
        assertOfferingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferingAllUpdatablePropertiesEquals(Offering expected, Offering actual) {
        assertOfferingUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferingAutoGeneratedPropertiesEquals(Offering expected, Offering actual) {
        assertThat(actual)
            .as("Verify Offering auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferingUpdatableFieldsEquals(Offering expected, Offering actual) {
        assertThat(actual)
            .as("Verify Offering relevant properties")
            .satisfies(a -> assertThat(a.getDurationMinutes()).as("check durationMinutes").isEqualTo(expected.getDurationMinutes()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()));
    }
}
