package hu.daniinc.reservation.domain;

import static hu.daniinc.reservation.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class WorkingHoursAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingHoursAllPropertiesEquals(WorkingHours expected, WorkingHours actual) {
        assertWorkingHoursAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkingHoursAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingHoursAllUpdatablePropertiesEquals(WorkingHours expected, WorkingHours actual) {
        assertWorkingHoursUpdatableFieldsEquals(expected, actual);
        assertWorkingHoursUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingHoursAutoGeneratedPropertiesEquals(WorkingHours expected, WorkingHours actual) {
        assertThat(actual)
            .as("Verify WorkingHours auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingHoursUpdatableFieldsEquals(WorkingHours expected, WorkingHours actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkingHoursUpdatableRelationshipsEquals(WorkingHours expected, WorkingHours actual) {
        assertThat(actual)
            .as("Verify WorkingHours relationships")
            .satisfies(a -> assertThat(a.getBusiness()).as("check business").isEqualTo(expected.getBusiness()));
    }
}
