package hu.daniinc.reservation.domain.enumeration;

public enum BusinessPermission {
    VIEW_OWN_SCHEDULE,
    VIEW_ALL_SCHEDULE,
    EDIT_OWN_SCHEDULE,
    EDIT_ALL_SCHEDULES,
    CREATE_BOOKING,
    EDIT_OWN_BOOKINGS,
    EDIT_ALL_BOOKINGS,
    VIEW_SERVICES,
    EDIT_OWN_SERVICES,
    EDIT_ALL_SERVICES,
    MANAGE_EMPLOYEES,
    VIEW_EMPLOYEES,
    VIEW_ALL_GUESTS, //can view other employee's guests
    MANAGE_BUSINESS_SETTINGS,
    EDIT_OWN_WORKING_HOURS,
    EDIT_ALL_WORKING_HOURS,
    VIEW_OWN_STATISTICS,
    VIEW_ALL_STATISTICS,
}
